"""DeviceAdapter protocol."""

from __future__ import annotations

from typing import AsyncIterator, Protocol, runtime_checkable


@runtime_checkable
class DeviceAdapter(Protocol):
    async def acquire(self) -> None: ...
    async def reset(self) -> None: ...
    async def flash(self, artifact: dict) -> None: ...
    async def open_serial(self) -> AsyncIterator[bytes]: ...
    async def release(self) -> None: ...
